// Generated by tools/generate_typescript.py. Do not edit by hand.
export const TELEMETRY_SCHEMA_VERSION = '1.2' as const;
export const API_VERSION = 'v1' as const;

export type EventType =
  | 'pipeline_started'
  | 'snapshot_created'
  | 'market_context_ready'
  | 'agent_started'
  | 'agent_signal_emitted'
  | 'council_round_started'
  | 'council_decision_emitted'
  | 'risk_evaluation_started'
  | 'risk_decision_emitted'
  | 'risk_vetoed'
  | 'order_approved'
  | 'execution_started'
  | 'execution_report_emitted'
  | 'portfolio_updated'
  | 'reconciliation_completed'
  | 'pipeline_completed'
  | 'pipeline_failed'
  | 'backtest_started'
  | 'backtest_progress'
  | 'backtest_completed';

export type TelemetryPayload =
  | SnapshotPayload
  | MarketContextPayload
  | AgentSignalPayload
  | CouncilDecisionPayload
  | RiskDecisionPayload
  | ApprovedOrderPayload
  | ExecutionReportPayload
  | PortfolioPayload
  | ReconciliationPayload
  | StagePayload
  | PipelineFailedPayload
  | BacktestPayload;

export interface TelemetryEventMap {
  readonly pipeline_started: StagePayload;
  readonly snapshot_created: SnapshotPayload;
  readonly market_context_ready: MarketContextPayload;
  readonly agent_started: StagePayload;
  readonly agent_signal_emitted: AgentSignalPayload;
  readonly council_round_started: StagePayload;
  readonly council_decision_emitted: CouncilDecisionPayload;
  readonly risk_evaluation_started: StagePayload;
  readonly risk_decision_emitted: RiskDecisionPayload;
  readonly risk_vetoed: RiskDecisionPayload;
  readonly order_approved: ApprovedOrderPayload;
  readonly execution_started: StagePayload;
  readonly execution_report_emitted: ExecutionReportPayload;
  readonly portfolio_updated: PortfolioPayload;
  readonly reconciliation_completed: ReconciliationPayload;
  readonly pipeline_completed: StagePayload;
  readonly pipeline_failed: PipelineFailedPayload;
  readonly backtest_started: BacktestPayload;
  readonly backtest_progress: BacktestPayload;
  readonly backtest_completed: BacktestPayload;
}

export type TypedTelemetryEvent = {
  [K in EventType]: Omit<TelemetryEvent, 'event_type' | 'payload'> & {
    readonly event_type: K;
    readonly payload: TelemetryEventMap[K];
  };
}[EventType];

export interface MarketBarPayload {
  readonly opened_at: string;
  readonly closed_at: string;
  readonly available_at: string;
  readonly open: number;
  readonly high: number;
  readonly low: number;
  readonly close: number;
  readonly volume: number;
}

export interface SnapshotProvenancePayload {
  readonly provider: string;
  readonly instrument: string;
  readonly timeframe: string;
  readonly requested_start: string;
  readonly requested_end: string;
  readonly as_of: string;
  readonly fetched_at: string;
  readonly latest_observation_time: string;
  readonly latest_available_at: string;
  readonly source_version: string;
  readonly adapter_version: string;
  readonly coverage_complete: boolean;
  readonly cache_key: string;
}

export interface SnapshotPayload {
  readonly snapshot_id: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly as_of: string;
  readonly observed_at: string;
  readonly latest_available_at: string;
  readonly bars: ReadonlyArray<MarketBarPayload>;
  readonly provenance: SnapshotProvenancePayload | null;
}

export interface ContextProvenancePayload {
  readonly provider: string;
  readonly source_id: string;
  readonly observed_at: string;
  readonly period_start: string | null;
  readonly period_end: string | null;
  readonly published_at: string | null;
  readonly provider_available_at: string;
  readonly ingested_at: string;
  readonly vintage: string;
  readonly revision: string | null;
  readonly source_version: string;
}

export interface ContextDatumPayload {
  readonly capability: string;
  readonly instrument: string;
  readonly name: string;
  readonly value: unknown;
  readonly unit: string;
  readonly provenance: ContextProvenancePayload;
}

export interface MarketContextPayload {
  readonly context_id: string;
  readonly snapshot_id: string;
  readonly as_of: string;
  readonly data: ReadonlyArray<ContextDatumPayload>;
  readonly requested_required: ReadonlyArray<string>;
  readonly requested_optional: ReadonlyArray<string>;
  readonly missing_required: ReadonlyArray<string>;
  readonly missing_optional: ReadonlyArray<string>;
}

export interface VolatilityPayload {
  readonly estimator: string;
  readonly window_bars: number;
  readonly units: string;
  readonly observed_at: string;
  readonly source_snapshot_id: string;
  readonly status: string;
  readonly value: number | null;
}

export interface AgentSignalPayload {
  readonly signal_id: string;
  readonly domain_schema_version: string;
  readonly agent_id: string;
  readonly agent_version: string;
  readonly signal_type: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly source_snapshot_id: string;
  readonly source_as_of: string;
  readonly forecast_direction: string;
  readonly expected_return: number | null;
  readonly target_exposure: number | null;
  readonly action: string;
  readonly validity: string;
  readonly confidence: number;
  readonly horizon_bars: number;
  readonly generated_at: string;
  readonly expires_at: string;
  readonly rationale: string;
  readonly volatility: VolatilityPayload | null;
  readonly metadata: Record<string, unknown>;
}

export interface CouncilDecisionPayload {
  readonly decision_id: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly source_snapshot_id: string;
  readonly source_as_of: string;
  readonly forecast_direction: string;
  readonly expected_return: number | null;
  readonly target_exposure: number | null;
  readonly action: string;
  readonly conviction: number;
  readonly confidence: number;
  readonly decided_at: string;
  readonly expires_at: string;
  readonly rationale: string;
  readonly signal_ids: ReadonlyArray<string>;
  readonly participating_agent_ids: ReadonlyArray<string>;
}

export interface ApprovedOrderPayload {
  readonly order_id: string;
  readonly decision_id: string;
  readonly source_snapshot_id: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly side: string;
  readonly quantity: number;
  readonly reference_price: number;
  readonly authorized_at: string;
  readonly earliest_fill_at: string;
  readonly expires_at: string;
  readonly fill_policy: string;
  readonly max_fee_bps: number;
  readonly max_slippage_bps: number;
  readonly reduce_only: boolean;
  readonly paper_only: true;
}

export interface RiskDecisionPayload {
  readonly risk_status: string;
  readonly approved: boolean;
  readonly vetoed: boolean;
  readonly reasons: ReadonlyArray<string>;
  readonly policy_check_ids: ReadonlyArray<string>;
  readonly evaluated_at: string;
  readonly decision_id: string;
  readonly source_snapshot_id: string;
  readonly approved_order: ApprovedOrderPayload | null;
  readonly cash: number;
  readonly equity: number;
  readonly gross_exposure: number;
  readonly position_quantity: number;
}

export interface ExecutionReportPayload {
  readonly order_id: string;
  readonly decision_id: string;
  readonly symbol: string;
  readonly side: string;
  readonly quantity: number;
  readonly submitted_at: string;
  readonly filled_at: string | null;
  readonly fill_price: number | null;
  readonly fees: number;
  readonly slippage_bps: number;
  readonly slippage_cost: number | null;
  readonly total_costs: number | null;
  readonly execution_status: string;
  readonly message: string;
  readonly paper_only: true;
}

export interface PositionPayload {
  readonly symbol: string;
  readonly quantity: number;
  readonly average_entry_price: number;
  readonly mark_price: number;
  readonly mark_observed_at: string;
  readonly market_value: number;
  readonly unrealized_pnl: number;
  readonly exposure: number;
}

export interface PortfolioPayload {
  readonly cash: number;
  readonly equity: number;
  readonly positions: ReadonlyArray<PositionPayload>;
  readonly gross_exposure: number;
  readonly unrealized_pnl: number;
  readonly valued_at: string;
}

export interface ReconciliationPayload {
  readonly decision_id: string;
  readonly order_id: string;
  readonly compliant: boolean;
  readonly reconciled_at: string;
  readonly reasons: ReadonlyArray<string>;
}

export interface StagePayload {
  readonly stage: string;
  readonly message: string;
  readonly agent_id: string | null;
  readonly agent_version: string | null;
  readonly decision_id: string | null;
  readonly order_id: string | null;
  readonly total_agents: number | null;
}

export interface PipelineFailedPayload {
  readonly stage: string;
  readonly error_code: string;
  readonly message: string;
}

export interface BacktestPayload {
  readonly status: 'started' | 'in_progress' | 'completed';
  readonly current: number;
  readonly total: number | null;
  readonly progress: number | null;
  readonly event_count: number | null;
  readonly trade_count: number | null;
}

export interface TelemetryEvent {
  readonly event_id: string;
  readonly event_type: EventType;
  readonly schema_version: '1.2';
  readonly stream_id: string | null;
  readonly sequence: number;
  readonly run_id: string;
  readonly symbol: string | null;
  readonly timeframe: string | null;
  readonly emitted_at: string;
  readonly source_snapshot_id: string | null;
  readonly correlation_id: string | null;
  readonly payload: SnapshotPayload | MarketContextPayload | AgentSignalPayload | CouncilDecisionPayload | RiskDecisionPayload | ApprovedOrderPayload | ExecutionReportPayload | PortfolioPayload | ReconciliationPayload | StagePayload | PipelineFailedPayload | BacktestPayload;
}

export interface ApiError {
  readonly code: string;
  readonly message: string;
  readonly details: unknown | null;
  readonly request_id: string;
}

export interface ErrorResponse {
  readonly api_version: 'v1';
  readonly error: ApiError;
}

export interface HealthResponse {
  readonly api_version: 'v1';
  readonly status: 'ok';
  readonly service: 'botnet-council-telemetry';
  readonly backend_version: string;
  readonly read_only: boolean;
  readonly capabilities: ReadonlyArray<'telemetry_read' | 'experiment_read' | 'experience_read' | 'learning_read' | 'experiment_control'>;
  readonly command_authentication: 'disabled' | 'bearer_token';
}

export interface StateResponse {
  readonly api_version: 'v1';
  readonly stream_id: string;
  readonly sequence_watermark: number;
  readonly event_count: number;
  readonly last_sequence: number;
  readonly latest_portfolio: PortfolioPayload | null;
  readonly latest_decision: CouncilDecisionPayload | null;
  readonly latest_risk_decision: RiskDecisionPayload | null;
  readonly active_runs: ReadonlyArray<string>;
}

export interface PortfolioResponse {
  readonly api_version: 'v1';
  readonly portfolio: PortfolioPayload;
}

export interface EventPage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<TelemetryEvent>;
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export interface DecisionDetailResponse {
  readonly api_version: 'v1';
  readonly decision_id: string;
  readonly events: ReadonlyArray<TelemetryEvent>;
}

export interface RunSummary {
  readonly run_id: string;
  readonly run_kind: 'pipeline' | 'backtest';
  readonly first_sequence: number;
  readonly last_sequence: number;
  readonly started_at: string;
  readonly updated_at: string;
  readonly event_count: number;
  readonly status: 'running' | 'completed' | 'failed';
  readonly symbol: string | null;
  readonly timeframe: string | null;
}

export interface RunPage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<RunSummary>;
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export interface RunDetailResponse {
  readonly api_version: 'v1';
  readonly run_id: string;
  readonly events: ReadonlyArray<TelemetryEvent>;
}

export interface SnapshotResponse {
  readonly api_version: 'v1';
  readonly snapshot: SnapshotPayload;
}

export interface AgentSummary {
  readonly agent_id: string;
  readonly agent_version: string;
  readonly latest_signal: TelemetryEvent;
}

export interface AgentPage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<AgentSummary>;
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export interface AgentDetailResponse {
  readonly api_version: 'v1';
  readonly agent_id: string;
  readonly signals: ReadonlyArray<TelemetryEvent>;
}

export interface BootstrapResponse {
  readonly api_version: 'v1';
  readonly stream_id: string;
  readonly sequence_watermark: number;
  readonly state: StateResponse;
  readonly runs: ReadonlyArray<RunSummary>;
  readonly agents: ReadonlyArray<AgentSummary>;
  readonly events: ReadonlyArray<TelemetryEvent>;
}

export interface AppliedWeightPayload {
  readonly agent_id: string;
  readonly weight: number;
}

export interface ExperienceSummaryPayload {
  readonly episode_id: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly decision_timestamp: string;
  readonly weight_generation_id: string;
  readonly regime: string | null;
  readonly training_eligible: boolean;
  readonly forecast_direction: string;
  readonly expected_return: number | null;
  readonly realized_return: number | null;
  readonly directional_correctness: boolean | null;
  readonly maximum_adverse_excursion: number | null;
  readonly maximum_favorable_excursion: number | null;
}

export interface ExperienceDetailPayload {
  readonly episode_id: string;
  readonly symbol: string;
  readonly timeframe: string;
  readonly decision_timestamp: string;
  readonly weight_generation_id: string;
  readonly regime: string | null;
  readonly training_eligible: boolean;
  readonly forecast_direction: string;
  readonly expected_return: number | null;
  readonly realized_return: number | null;
  readonly directional_correctness: boolean | null;
  readonly maximum_adverse_excursion: number | null;
  readonly maximum_favorable_excursion: number | null;
  readonly decision: CouncilDecisionPayload;
  readonly specialist_outputs: ReadonlyArray<AgentSignalPayload>;
  readonly applied_weights: ReadonlyArray<AppliedWeightPayload>;
  readonly backtest_run_id: string;
  readonly risk_policy_version: string;
  readonly truth_available_at: string | null;
}

export interface ExperiencePage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<ExperienceSummaryPayload>;
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export interface ExperienceResponse {
  readonly api_version: 'v1';
  readonly episode: ExperienceDetailPayload;
}

export interface WeightScopePayload {
  readonly asset_class: string | null;
  readonly symbol: string | null;
  readonly regime: string | null;
  readonly horizon_bars: number | null;
}

export interface AdaptiveWeightPayload {
  readonly long_term: number;
  readonly recent: number;
  readonly recent_mix: number;
  readonly effective: number;
}

export interface ScopedAgentWeightPayload {
  readonly agent_id: string;
  readonly scope: WeightScopePayload;
  readonly weight: AdaptiveWeightPayload;
}

export interface WeightGenerationPayload {
  readonly generation: number;
  readonly generation_id: string;
  readonly parent_generation_id: string | null;
  readonly created_at: string;
  readonly scoring_version: string;
  readonly profile_id: string;
  readonly entries: ReadonlyArray<ScopedAgentWeightPayload>;
}

export interface WeightGenerationPage {
  readonly api_version: 'v1';
  readonly active_generation_id: string | null;
  readonly items: ReadonlyArray<WeightGenerationPayload>;
  readonly total: number;
}

export interface EvaluationMetricsPayload {
  readonly episode_count: number;
  readonly total_return: number;
  readonly benchmark_relative_return: number;
  readonly maximum_drawdown: number;
  readonly hit_rate: number;
  readonly mean_calibration_error: number;
  readonly risk_adjusted_return: number;
  readonly turnover: number;
  readonly cost_adjusted_return: number;
  readonly worst_slice_return: number;
  readonly score: number;
}

export interface WeightChangePayload {
  readonly agent_id: string;
  readonly scope: WeightScopePayload;
  readonly current: AdaptiveWeightPayload;
  readonly proposed: AdaptiveWeightPayload;
  readonly sample_count: number;
  readonly confidence: number;
  readonly long_term_accuracy: number | null;
  readonly recent_accuracy: number | null;
  readonly reason: string;
}

export interface LearningReviewPayload {
  readonly result_id: string;
  readonly proposal_id: string;
  readonly base_generation_id: string;
  readonly decision: 'accept' | 'reject' | 'accept_reduced_update';
  readonly created_at: string;
  readonly training_cutoff: string;
  readonly evaluated_at: string;
  readonly librarian_version: string;
  readonly teacher_version: string;
  readonly scoring_version: string;
  readonly training_episode_count: number;
  readonly held_out_episode_count: number;
  readonly changes: ReadonlyArray<WeightChangePayload>;
  readonly accepted_changes: ReadonlyArray<WeightChangePayload>;
  readonly baseline: EvaluationMetricsPayload;
  readonly proposed: EvaluationMetricsPayload;
  readonly reasons: ReadonlyArray<string>;
}

export interface LearningReviewPage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<LearningReviewPayload>;
  readonly total: number;
}

export interface ExperimentAgentRequest {
  readonly kind: 'trend' | 'mean_reversion' | 'volatility' | 'regime' | 'seasonality' | 'historical_recurrence';
  readonly parameters: Record<string, number | number>;
}

export interface ExperimentCouncilRequest {
  readonly agent_weights: Record<string, number>;
  readonly minimum_confidence: number;
  readonly minimum_conviction: number;
}

export interface ExperimentCreateRequest {
  readonly instrument: string;
  readonly provider: 'kraken' | 'in_memory';
  readonly evaluation_time: string;
  readonly forecast_horizon: string;
  readonly timeframe: string;
  readonly agents: ReadonlyArray<ExperimentAgentRequest>;
  readonly council: ExperimentCouncilRequest;
  readonly random_seed: number | null;
  readonly context_bars: number | null;
}

export interface RandomExperimentCreateRequest {
  readonly template: ExperimentCreateRequest;
  readonly range_start: string;
  readonly range_end: string;
  readonly samples: number;
  readonly seed: number;
}

export interface ExperimentRequestPayload {
  readonly instrument: string;
  readonly provider: string;
  readonly evaluation_time: string;
  readonly forecast_horizon: string;
  readonly timeframe: string;
  readonly agents: ReadonlyArray<ExperimentAgentRequest>;
  readonly council: ExperimentCouncilRequest;
  readonly random_seed: number | null;
  readonly context_bars: number | null;
}

export interface ExperimentLifecyclePayload {
  readonly state: string;
  readonly occurred_at: string;
  readonly message: string;
}

export interface ExperimentProvenancePayload {
  readonly provider: string;
  readonly request_start: string;
  readonly request_end: string;
  readonly as_of: string;
  readonly fetched_at: string;
  readonly source_version: string;
  readonly adapter_semantic_version: string;
  readonly cache_key: string;
  readonly content_identity: string;
  readonly snapshot_id: string | null;
}

export interface ExperimentForecastPayload {
  readonly forecast_id: string;
  readonly experiment_id: string;
  readonly evaluation_time: string;
  readonly instrument: string;
  readonly forecast_horizon: string;
  readonly expected_return: number | null;
  readonly direction: string;
  readonly confidence: number;
  readonly agent_forecasts: ReadonlyArray<AgentSignalPayload>;
  readonly council_decision: CouncilDecisionPayload;
  readonly council_weights: Record<string, number>;
  readonly source_provenance: ExperimentProvenancePayload;
  readonly agent_versions: Record<string, string>;
  readonly finalized_at: string;
}

export interface ExperimentOraclePayload {
  readonly experiment_id: string;
  readonly evaluation_time: string;
  readonly horizon_end: string;
  readonly price_convention: string;
  readonly start_price: number | null;
  readonly endpoint_price: number | null;
  readonly realized_return: number | null;
  readonly realized_direction: string | null;
  readonly maximum_favorable_excursion: number | null;
  readonly maximum_adverse_excursion: number | null;
  readonly data_provenance: ExperimentProvenancePayload;
  readonly horizon_complete: boolean;
}

export interface ExperimentEvaluationPayload {
  readonly experiment_id: string;
  readonly forecast_id: string;
  readonly directional_correctness: boolean;
  readonly forecast_direction: string;
  readonly realized_direction: string;
  readonly expected_return: number | null;
  readonly realized_return: number;
  readonly absolute_return_error: number | null;
  readonly signed_return_error: number | null;
  readonly confidence: number;
  readonly calibration_bucket: string;
  readonly evaluated_at: string;
}

export interface ExperimentSummaryPayload {
  readonly experiment_id: string;
  readonly state: string;
  readonly request: ExperimentRequestPayload;
  readonly lifecycle: ReadonlyArray<ExperimentLifecyclePayload>;
  readonly forecast_locked: boolean;
  readonly oracle_available: boolean;
  readonly evaluation_available: boolean;
  readonly error: string | null;
}

export interface ExperimentResponse {
  readonly api_version: 'v1';
  readonly experiment: ExperimentSummaryPayload;
}

export interface ExperimentPage {
  readonly api_version: 'v1';
  readonly items: ReadonlyArray<ExperimentSummaryPayload>;
  readonly total: number;
  readonly limit: number;
  readonly offset: number;
}

export interface ExperimentForecastResponse {
  readonly api_version: 'v1';
  readonly forecast: ExperimentForecastPayload;
}

export interface ExperimentOracleResponse {
  readonly api_version: 'v1';
  readonly oracle_outcome: ExperimentOraclePayload;
}

export interface ExperimentEvaluationResponse {
  readonly api_version: 'v1';
  readonly evaluation: ExperimentEvaluationPayload;
}

export interface CalibrationBucketPayload {
  readonly bucket: string;
  readonly count: number;
  readonly mean_confidence: number;
  readonly directional_accuracy: number;
}

export interface ConfigurationPerformancePayload {
  readonly configuration_id: string;
  readonly experiment_count: number;
  readonly directional_accuracy: number;
  readonly mean_absolute_return_error: number | null;
  readonly forecast_bias: number | null;
}

export interface ExperimentBatchResponse {
  readonly api_version: 'v1';
  readonly batch_id: string;
  readonly selection_seed: number;
  readonly experiment_ids: ReadonlyArray<string>;
  readonly experiment_count: number;
  readonly directional_accuracy: number;
  readonly mean_absolute_return_error: number | null;
  readonly forecast_bias: number | null;
  readonly confidence_calibration: ReadonlyArray<CalibrationBucketPayload>;
  readonly performance_by_configuration: ReadonlyArray<ConfigurationPerformancePayload>;
}
