"""Generate the frontend contract directly from the public Pydantic models."""

from __future__ import annotations

import argparse
import types
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Literal, Union, get_args, get_origin

from pydantic import BaseModel

from botnet_council.telemetry import contracts

MODELS: tuple[type[BaseModel], ...] = (
    contracts.MarketBarPayload,
    contracts.SnapshotProvenancePayload,
    contracts.SnapshotPayload,
    contracts.VolatilityPayload,
    contracts.AgentSignalPayload,
    contracts.CouncilDecisionPayload,
    contracts.ApprovedOrderPayload,
    contracts.RiskDecisionPayload,
    contracts.ExecutionReportPayload,
    contracts.PositionPayload,
    contracts.PortfolioPayload,
    contracts.ReconciliationPayload,
    contracts.StagePayload,
    contracts.PipelineFailedPayload,
    contracts.BacktestPayload,
    contracts.TelemetryEvent,
    contracts.ApiError,
    contracts.ErrorResponse,
    contracts.HealthResponse,
    contracts.StateResponse,
    contracts.PortfolioResponse,
    contracts.EventPage,
    contracts.DecisionDetailResponse,
    contracts.RunSummary,
    contracts.RunPage,
    contracts.RunDetailResponse,
    contracts.SnapshotResponse,
    contracts.AgentSummary,
    contracts.AgentPage,
    contracts.AgentDetailResponse,
    contracts.BootstrapResponse,
)


def typescript_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    arguments = get_args(annotation)
    if origin is Annotated:
        return typescript_type(arguments[0])
    if origin in (Union, types.UnionType):
        return " | ".join(typescript_type(item) for item in arguments)
    if origin is Literal:
        return " | ".join(_literal(item) for item in arguments)
    if origin is tuple:
        if len(arguments) == 2 and arguments[1] is Ellipsis:
            return f"ReadonlyArray<{typescript_type(arguments[0])}>"
        return "readonly [" + ", ".join(typescript_type(item) for item in arguments) + "]"
    if origin is dict:
        return f"Record<{typescript_type(arguments[0])}, {typescript_type(arguments[1])}>"
    if annotation is Any:
        return "unknown"
    if annotation is None or annotation is type(None):
        return "null"
    if annotation is datetime:
        return "string"
    if annotation is str:
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return annotation.__name__
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    raise TypeError(f"unsupported public type annotation: {annotation!r}")


def _literal(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, str):
        return repr(value)
    return str(value)


def render() -> str:
    lines = [
        "// Generated by tools/generate_typescript.py. Do not edit by hand.",
        f"export const TELEMETRY_SCHEMA_VERSION = '{contracts.SCHEMA_VERSION}' as const;",
        f"export const API_VERSION = '{contracts.API_VERSION}' as const;",
        "",
        "export type EventType =",
    ]
    values = list(contracts.EventType)
    lines.extend(
        f"  | '{item.value}'{';' if index == len(values) - 1 else ''}"
        for index, item in enumerate(values)
    )
    lines.extend(("", "export type TelemetryPayload ="))
    payloads = get_args(get_args(contracts.TelemetryPayload)[0])
    lines.extend(
        f"  | {item.__name__}{';' if index == len(payloads) - 1 else ''}"
        for index, item in enumerate(payloads)
    )
    lines.extend(("", "export interface TelemetryEventMap {"))
    for event_type in contracts.EventType:
        payload = contracts._PAYLOAD_TYPES.get(event_type, contracts.StagePayload)
        lines.append(f"  readonly {event_type.value}: {payload.__name__};")
    lines.extend(
        (
            "}",
            "",
            "export type TypedTelemetryEvent = {",
            "  [K in EventType]: Omit<TelemetryEvent, 'event_type' | 'payload'> & {",
            "    readonly event_type: K;",
            "    readonly payload: TelemetryEventMap[K];",
            "  };",
            "}[EventType];",
        )
    )
    for model in MODELS:
        lines.extend(("", f"export interface {model.__name__} {{"))
        for name, field in model.model_fields.items():
            lines.append(f"  readonly {name}: {typescript_type(field.annotation)};")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--output", default="contracts/typescript/types.generated.ts", type=Path
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else None
        return 0 if current == expected else 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
